from io import BytesIO
from datetime import datetime
import random
import tempfile

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)


class PDFGenerator:

    def generate(
        self,
        decision,
        uploaded_file,
        customer_id,
        claim_object
    ):

        buffer = BytesIO()

        doc = SimpleDocTemplate(buffer)

        styles = getSampleStyleSheet()

        story = []

        report_id = (
            f"CV-{datetime.now().strftime('%Y%m%d')}-"
            f"{random.randint(1000,9999)}"
        )

        # ==========================
        # Header
        # ==========================

        story.append(
            Paragraph(
                "<font size=24 color='#2563EB'><b>ClaimVision AI</b></font>",
                styles["Title"]
            )
        )

        story.append(
            Paragraph(
                "<b>AI Powered Insurance Claim Verification</b>",
                styles["Heading2"]
            )
        )

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                f"<b>Report ID:</b> {report_id}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
                styles["Normal"]
            )
        )

        story.append(Spacer(1, 20))

        # ==========================
        # Customer Information
        # ==========================

        story.append(
            Paragraph("<b>Customer Information</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(f"Customer ID : {customer_id}", styles["Normal"])
        )

        story.append(
            Paragraph(f"Claim Object : {claim_object.title()}", styles["Normal"])
        )

        story.append(Spacer(1, 15))

        # ==========================
        # Uploaded Image
        # ==========================

        if uploaded_file is not None:

            temp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")

            temp.write(uploaded_file.getvalue())

            temp.close()

            img = Image(temp.name)

            img.drawWidth = 4 * inch
            img.drawHeight = 3 * inch

            story.append(img)

            story.append(Spacer(1, 20))

        # ==========================
        # Claim Status
        # ==========================

        status = decision["claim_status"]

        if status == "supported":
            status_text = "🟢 SUPPORTED"

        elif status == "contradicted":
            status_text = "🔴 CONTRADICTED"

        else:
            status_text = "🟡 NOT ENOUGH INFORMATION"

        story.append(
            Paragraph("<b>Claim Decision</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(status_text, styles["Normal"])
        )

        story.append(Spacer(1, 20))

        # ==========================
        # Analysis Summary
        # ==========================

        data = [

            ["Field", "Value"],

            ["Severity", decision["severity"].upper()],

            ["Issue Type", decision["issue_type"].replace("_", " ").title()],

            ["Damaged Part", decision["object_part"] or "N/A"],

            ["Evidence Standard", decision["evidence_standard_met"]],

        ]

        table = Table(data, colWidths=[180, 250])

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (0, -1), colors.lightgrey),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

            ])

        )

        story.append(table)

        story.append(Spacer(1, 20))

        # ==========================
        # AI Explanation
        # ==========================

        story.append(
            Paragraph("<b>AI Explanation</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(
                decision["claim_status_justification"],
                styles["BodyText"]
            )
        )

        story.append(Spacer(1, 30))

        # ==========================
        # Footer
        # ==========================

        story.append(
            Paragraph(
                "<b>Generated by ClaimVision AI</b>",
                styles["Heading3"]
            )
        )

        story.append(
            Paragraph(
                "This report was generated using Google Gemini AI for insurance claim verification. "
                "It should be reviewed by an authorized claim officer before final approval.",
                styles["BodyText"]
            )
        )

        doc.build(story)

        pdf = buffer.getvalue()

        buffer.close()

        return pdf